version: '2'
services:
  node:
    networks:
      - amazeeio-network
      - default
    build:
      context: .
      dockerfile: node.dockerfile
    labels:
      lagoon.type: node
    volumes:
      - ./src:/app/src:delegated
    environment:
      - LAGOON_LOCALDEV_HTTP_PORT=3000
      - LAGOON_ROUTE=http://node.docker.amazee.io

networks:
  amazeeio-network:
    external: true
